- hosts: all
  remote_user: vagrant
  become: yes
  connection: local
  gather_facts: no
  tasks:
  - name: install nginx
    apt: name=nginx state=latest update_cache=yes
    register: result
    until: result|success
    retries: 3
    delay: 1
    notify: restart nginx
    ignore_errors: yes
  - name: display error
    debug: var=result.stderr verbosity=3
  - name: update config
    file: name=/usr/share/nginx/www state=absent
  - name: update config again
    file: src=/vagrant dest=/usr/share/nginx/www state=link
  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
