# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.box_check_update = false
  config.vm.define "ubu01" do |ubu|
	ubu.vm.hostname = "ubu01"
	ubu.vm.network "private_network", type: "dhcp"
        ubu.vm.network "forwarded_port", guest: 80, host: 8090
  end
  config.vm.provider "virtualbox" do |vb|
  	vb.name = "ubu01"
  end
  config.vm.provision "ansible" do |ansible|
	ansible.playbook = 'playbook.yml'
  end
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
